services:
  productservice:
    image: productservice
    build:
      context: .
      dockerfile: ProductService/Dockerfile

  orderservice:
    image: orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile

  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile

